version: "3.9"

networks:
  unitime_net:
    driver: "bridge"

services:
  db:
    container_name: "db"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql/data:/var/lib/mysql
    networks:
      - unitime_net

  tomcat:
    container_name: "tomcat"
    image: tomcat:9.0.56-jre8
    restart: always
    environment:
      CATALINA_BASE: /usr/local/tomcat
      CATALINA_HOME: /usr/local/tomcat
      JAVA_OPTS: "-Xmx8192m"
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - "./storage/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml"
      - "./storage/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./storage/tomcat/conf/web.xml:/usr/local/tomcat/conf/web.xml"
      - "./storage/tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml"
      - "./storage/tomcat/conf/logging.properties:/usr/local/tomcat/conf/logging.properties"
      - "./storage/tomcat/conf/catalina.properties:/usr/local/tomcat/conf/catalina.properties"
      - "./storage/tomcat/conf/unitime.properties:/usr/local/tomcat/conf/unitime.properties"
      # Web app
      - "./storage/tomcat/web:/usr/local/tomcat/webapps"
      # MySQL connector lib
      - "./storage/tomcat/lib/mysql-connector-java-8.0.27.jar:/usr/local/tomcat/lib/mysql-connector-java-8.0.27.jar"
    networks:
      - unitime_net
